### ISSUE TITLE
Language support?

### ISSUE THREAD

**Issue by Masaru2** [scbroede/dq4-partychat-patcher#2]
If you play in languages other than English, the party chat throws a message error

Is there any chance that other languages packed in the NA rom (French, Spanish) are going to be supported in the future, or its unlikely because of the rom size?

**Comment by scbroede** [comment]
rom size isn't an issue, the files for the other 4 languages could probably fit in the rom without going over the original size. even if they didn't, exceeding the original rom size wouldn't even be a problem (the largest ds roms are 4x the size of dq4's rom)

the changes to the game's code i made should work for every language (which is how you're getting those error messages in the first place instead of having nothing happen), but the reason other languages don't work is because only the english .mpt files with the party chat script are added as part of the patching process. if you were to unpack the rom you have again, insert the .mpt files for other languages (in MESS/fr, MESS/es, etc.), and repack it, the other languages would probably start *mostly* working too. don't add the other languages as part of the initial patching process though, because it will mess up the xdelta in the final step. only do this once you've finished the patching process.

the problem though is that these .mpt files would be unpatched and therefore have a few minor formatting issues in-game. unfortunately mptpatcher.py is built with the english .mpt files in mind and probably won't completely work with the files for the other languages. if someone wants to fix that i'd accept a pull request, or i might get around to doing it myself at some point. will leave this issue open until that gets done

**Comment by scbroede** [comment]
so when i wrote that i had assumed there were already french/spanish etc. languages in the mobile version, but now that i've gotten around to checking it turns out that this doesn't seem to be the case.

with that in mind, supporting the other languages isn't a simple matter of patching mpt files; it would require actually translating them. given that i'm not fluent in any of those languages, i obviously won't be doing that. sorry if i got anyone's hopes up.

the stuff i said above should still be somewhat true though; the only work that needs to be done is translating the mpt files with the party chat text. once that's done they can be added to the MESS/fr, MESS/es, etc. folders using dslazy and everything should work. if anyone is interested in translating the party chat to one of those languages, i would recommend they check out the tool [here](https://gbatemp.net/threads/release-dragon-quest-iv-v-vi-ds-text-editor.650812/), which should help them
