### ISSUE TITLE
Menu cursor still defaults to "Items" instead of "Talk"

### ISSUE THREAD

**Issue by TiredTeddybear** [scbroede/dq4-partychat-patcher#3]
Hi, so one other change the NTSC-U version of DQ4 DS did was it made the main menu cursor default to "Items" instead of "Talk" whenever you open it. I assume this was done to further mask the removal of party chatting.

Here are some video examples.

NTSC-J: (18:36) https://www.youtube.com/watch?v=Zkh8HAi-1gw&t=1116s

NTSC-U: (18:24) https://www.youtube.com/watch?v=d7n1I2AyfwY&t=1104s

I know it's not a big issue since you can easily chat with your party using the B Button shortcut, but maybe it'd be another good restoration out of spite? Lol. And for what it's worth, the NTSC-U versions of of DQ5 and 6 DS kept the cursor on "Talk" when you open the menu.

**Comment by scbroede** [comment]
good catch. my goal with this is to make the game as close as possible to what an official release with party chat included might have looked like (which is why i restored the b-button shortcut despite it also not technically being required), and this would fall under that. the consistency with 5 and 6 is also a plus

**Comment by scbroede** [comment]
should be fixed as of the latest commit. feel free to reopen this issue if you notice anything wrong

**Comment by TiredTeddybear** [comment]
Thank you so much!
